# Generated by Django 5.1.2 on 2024-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
