# Generated by Django 5.1.2 on 2024-11-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
