# Generated by Django 5.1.2 on 2024-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_cpu_gpu_motherboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
