# Generated by Django 5.1.2 on 2024-11-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_psu_ram_ssd'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='psu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.psu'),
        ),
        migrations.AddField(
            model_name='build',
            name='ram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.ram'),
        ),
        migrations.AddField(
            model_name='build',
            name='ssd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.ssd'),
        ),
    ]
