# Generated by Django 5.1.2 on 2025-01-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_build_psu_build_ram_build_ssd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/cpus/'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/gpus/'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/motherboards/'),
        ),
        migrations.AddField(
            model_name='psu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/psus/'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/rams/'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/ssds/'),
        ),
    ]
