# Generated by Django 5.1.2 on 2025-01-07 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_cpu_rating_gpu_rating_motherboard_rating_psu_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.gpu')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.motherboard')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.psu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.ram')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.ssd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
