# Generated by Django 5.1.2 on 2025-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
