# Generated by Django 5.1.2 on 2025-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_remove_review_comment_remove_review_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
