# Generated by Django 5.1.2 on 2025-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_remove_review_comment_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='part_id',
            new_name='part',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='part_type',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
