# Generated by Django 5.1.2 on 2025-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_rename_content_review_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='part',
            new_name='part_id',
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
