# Generated by Django 5.1.2 on 2025-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_rename_comment_review_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='part_id',
        ),
        migrations.AddField(
            model_name='review',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
