# Generated by Django 5.1.2 on 2025-03-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parts', '0024_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='part_name',
        ),
        migrations.AddField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
