# Generated by Django 5.1.2 on 2025-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_remove_favorite_part_name_favorite_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='object_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
