# Generated by Django 5.1.2 on 2025-03-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_remove_favorite_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='tdp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
