# Generated by Django 5.1.2 on 2025-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_cpu_tdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='clock_speed',
            field=models.CharField(blank=True, null=True),
        ),
    ]
