# Generated by Django 5.1.2 on 2025-03-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_cpu_clock_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='rop',
            field=models.CharField(blank=True, null=True),
        ),
    ]
