# Generated by Django 5.1.2 on 2025-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_gpu_rop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssd',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
