# Generated by Django 5.1.2 on 2025-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0030_alter_ssd_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='socket_CPU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
