# Generated by Django 5.1.2 on 2025-03-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0031_cpu_socket_cpu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='socket_CPU',
            new_name='CPU_socket',
        ),
    ]
