# Generated by Django 5.1.2 on 2025-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0032_rename_socket_cpu_cpu_cpu_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='RAM_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
