# Generated by Django 5.1.2 on 2025-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0034_userrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrating',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
