# Generated by Django 5.1.2 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0035_alter_userrating_unique_together_userrating_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
