# Generated by Django 5.1.2 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0036_gpu_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='oem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
