# Generated by Django 5.1.2 on 2025-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0037_gpu_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
