# Generated by Django 5.1.2 on 2025-03-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0038_cpu_model_gpu_model_motherboard_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='part_name',
            new_name='part_model',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='part_name',
            new_name='part_model',
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='part_name',
            new_name='part_model',
        ),
    ]
