# Generated by Django 5.1.2 on 2025-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0039_rename_part_name_favorite_part_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
