# Generated by Django 5.1.2 on 2025-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0040_favorite_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
