# Generated by Django 5.1.2 on 2025-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0041_motherboard_product_link_psu_product_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
