# Generated by Django 5.1.2 on 2025-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0042_cpu_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
