# Generated by Django 5.1.2 on 2025-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_alter_cpu_model_alter_gpu_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='rating',
        ),
    ]
