# Generated by Django 5.1.2 on 2025-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0044_remove_cpu_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
