# Generated by Django 5.1.2 on 2025-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0045_alter_cpu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='description',
            field=models.TextField(),
        ),
    ]
