# Generated by Django 5.1.2 on 2025-03-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0046_alter_cpu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
