# Generated by Django 5.1.2 on 2025-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0048_cpu_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
