# Generated by Django 5.1.2 on 2025-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0049_cpu_watt_gpu_watt_motherboard_watt_ram_watt_ssd_watt'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
    ]
