# Generated by Django 5.1.2 on 2025-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0050_build_shareable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='gpu',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='psu',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='ram',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='ssd',
            name='details_link',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
