# Generated by Django 5.1.2 on 2025-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0051_cpu_details_link_gpu_details_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='details_link',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='details_link',
        ),
    ]
