# Generated by Django 5.1.2 on 2025-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0052_remove_cpu_details_link_remove_gpu_details_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/supra.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
