# Generated by Django 5.1.2 on 2025-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0053_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/stock.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
