# Generated by Django 5.1.2 on 2025-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0059_part_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartsSale',
        ),
    ]
